---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./restore.yaml
  - ./backup.yaml
  - ./gatus.yaml
configMapGenerator:
  - name: slskd-coredns
    files:
      - ./resources/Corefile
  - name: slskd-scripts
    files:
      - startup.sh=./resources/startup.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
