---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./aria2/ks.yaml
  - ./owntone/ks.yaml
  - ./transmission/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./plex/ks.yaml
  - ./syncthing/ks.yaml
  - ./metube/ks.yaml
  - ./kavita/ks.yaml
  - ./mylar/ks.yaml
