---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./emberstack-charts.yaml
  - ./external-dns.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./tailscale.yaml
  - ./weave-gitops.yaml
