---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - config-secrets.yaml
  - pvc.yaml
  - deploy.yaml
  - service.yaml
  - ingress.yaml
  - backuprepository.yaml
  - backupconfiguration.yaml
