---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - secrets.yaml
  - release.yaml
  - backupconfiguration.yaml
  - backuprepository.yaml
  # - exporter-deploy.yaml
  # - exporter-servicemonitor.yaml
  # - exporter-svc.yaml
