---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./qbittorrent/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./prowlarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./plex/ks.yaml
  - ./syncthing/ks.yaml
  - ./hass-nfs-mount-status/ks.yaml
  - ./tqm/ks.yaml
  - ./qbtagarr/ks.yaml
