---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./aria2/ks.yaml
  - ./kavita/ks.yaml
  - ./metube/ks.yaml
  - ./mylar/ks.yaml
  - ./owntone/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./syncthing/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./cross-seed/ks.yaml
  - ./autobrr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./slskd/ks.yaml
  - ./lidarr/ks.yaml
  - ./tqm/ks.yaml
  - ./upload-assistant/ks.yaml
  - ./navidrome/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./qbtagarr/ks.yaml
  - ./nemorosa/ks.yaml
