---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack-helm-repository.yaml
  - k8s-at-home-helm-repository.yaml
  - kubernetes-stable-helm-repository.yaml
  - longhorn-helm-repository.yaml
  - sealed-secrets-helm-repository.yaml
  - traefik-helm-repository.yaml
  - bananaspliff-helm-repository.yaml
  - vmware-tanzu-helm-repository.yaml
  - appcode-helm-repository.yaml
  - nicholaswilde-helm-repository.yaml
