---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gowon
resources:
  - ./checkiday
  - ./congratulations
  - ./donger
  - ./gotemplate
  - ./kbday
  - ./lastfm
  - ./markov
  # - ./morelike
  - ./pokedex
  - ./qwantz
  - ./retroachievements
  - ./steam
  - ./talk
  - ./tenor
  - ./trakt
  # - ./twitter
  - ./urls
  - ./wikipedia
  - ./wordnik
  - ./youtube
