---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./restore.yaml
  - ./backup.yaml
  - ./gatus.yaml
configMapGenerator:
  - name: qbittorrent-coredns
    files:
      - ./resources/Corefile
  - name: qbittorrent-scripts
    files:
      - gluetun-up.sh=./resources/gluetun-up.sh
      - torrent-added.sh=./resources/torrent-added.sh
      - torrent-finished.sh=./resources/torrent-finished.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
